### ISSUE TITLE
Deleted Homee devices are still in Home Assistant

### ISSUE THREAD

**Issue by MrAnDrs** [Taraman17/hass-homee#102]
## Type of problem
- [x] I have a question.
- [ ] A feature does not work as expected.
- [ ] I found a bug (see error log below).

## Version
2.9.6

## Detailed description
I deleted some devices in Homee within the last months, but all of them are still appearing within the Homee integration and cannot be deleted. Anything what I am doing wrong or can this be improved?

Please let me now if and which logs you might need.

**Comment by Taraman17** [comment]
Hi,
this is a difficult topic in HA:
https://community.home-assistant.io/t/how-can-i-delete-devices-i-dont-want-in-ha/236080/

Within this thread, I stumbled upon a post, that states that an integration may offer this functionality:
https://community.home-assistant.io/t/how-can-i-delete-devices-i-dont-want-in-ha/236080/18

I think automatic deletion would be quite dangerous, since a device may be absent momentarily for whatever reason. But offering the ability to manually delete stale devices sound logical to me, so I will have a look into this.

**Comment by MrAnDrs** [comment]
Hi, I personally would also be fine with the manual deletion possibility only. The automatic deletion I fully understand it is dangerous if not implemented bulletproof. For other integrations I somehow got this option offered in HA for longer time not-available devices, but not for the Homee ones. I have no clue what the difference is. 

As a workaround I deactivated the devices for now as the other workaround (deleting the whole integration and adding it again) would most probably mess up everything I set up  using the homee devices. :-)

Appreciate your work on this. Thanks!

**Comment by Taraman17** [comment]
This ended up being an easy one as it seems.

Test it with the latest beta if you like.

**Comment by MrAnDrs** [comment]
Tested it and the broken devices could be deleted, thanks!

What I am not sure if this might be improved: Now I can delete any device, not only the ones which are broken. "Jammern auf hohem Niveau" ;-), still it behaves different to other integrations where this is only working for the ones identified as broken (dont know how they do it in details). For another MQTT integration it showed something like "MQTT is not providing the device anymore". And these ones I could delete , but not the active ones. Maybe also custom implementation like if last update older than XXX add message and delete button?

**Comment by Taraman17** [comment]
You are right there.
I'll try to get that in for the final release.

**Comment by Taraman17** [comment]
I released a new beta, that only deletes devices that are not present in Homee anymore.
It uses the node's id and profile to identify it.

Caveat: If the user in the meanwhile adds another node, that gets the same id and has the same profile, the old device would not be deleted.
I'm not sure when Homee reuses previously used ids, but I think it does not immediately.
And even if this would happen, the device would show up again after next restart. So at most the history data could be lost, if this very remote case happens.

**Comment by Taraman17** [comment]
Closed with #113
