### ISSUE TITLE
Requirements for homee not found: ['websockets==12.0'] after Update to HAOS 2024.12

### ISSUE THREAD

**Issue by djkroko** [Taraman17/hass-homee#116]
## Type of problem
- [ ] I have a question.
- [ ] A feature does not work as expected.
- [x ] I found a bug (see error log below).

## Version
2.10

## Detailed description
After Update Home Assistant to 2024.12 the Error shows up:
Setup failed for custom integration 'homee': Requirements for homee not found: ['websockets==12.0']

**Comment by Taraman17** [comment]
Try the current beta (2.11.0-beta.1)
It should fix the problem.
I will prepare a release later.

**Comment by djkroko** [comment]
Thank you.
Beta release fixed the Issue

**Comment by Taraman17** [comment]
Fixed with release 2.11.0
