### ISSUE TITLE
Dimming value is sometimes overwritten with 100%

### ISSUE THREAD

**Issue by majacob1** [Taraman17/hass-homee#19]
## Type of problem

- [ ] I have a question.
- [ ] A feature does not work as expected.
- [X] I found a bug (see error log below).

## Version
2.6.1

## Detailed description
I'm using homee with the Warema Cube and want to control dimmable lights. When I set the dimming level to e.g. 10% it randomly jumps to 100%. This behaviour can not be observed when using the homee app.

**Comment by majacob1** [comment]
I modified light.py to only send on/off command if there's no dimming value specified - for my setup this is working, but I'm not sure, if this is also working for other dimmable lights:

        --- light.py.2.6.1	2023-10-08 09:56:25.708239798 +0200
        +++ light.py	2023-10-08 10:21:59.319111660 +0200
        @@ -216,12 +216,13 @@
         
             async def async_turn_on(self, **kwargs):
                 """Instruct the light to turn on."""
        -        await self.async_set_value_by_id(self._on_off_attr.id, 1)
         
                 if ATTR_BRIGHTNESS in kwargs and self._dimmer_attr is not None:
                     await self.async_set_value_by_id(
                         self._dimmer_attr.id, kwargs[ATTR_BRIGHTNESS] / 2.55
                     )
        +        else:
        +            await self.async_set_value_by_id(self._on_off_attr.id, 1)
                 if ATTR_COLOR_TEMP in kwargs and self._temp_attr is not None:
                     await self.async_set_value_by_id(
                         self._temp_attr.id,

**Comment by Taraman17** [comment]
The fix you propose is dependant on how lights handle the brightness setting. If every light turns on, when receiving a brightness value, this will work.
I'll have a look how other integrations handle this.

Another approach would be to add logging of the brightness value which is passed to the turn_on function, to see, why in your case it is erroneously set to 10%

**Comment by majacob1** [comment]
> Can you provide me with an info log as described in the readme?

[homee.log](https://github.com/Taraman17/hass-homee/files/13624884/homee.log)

**Comment by majacob1** [comment]
> The fix you propose is dependant on how lights handle the brightness setting. If every light turns on, when receiving a brightness value, this will work. I'll have a look how other integrations handle this.
> 
> Another approach would be to add logging of the brightness value which is passed to the turn_on function, to see, why in your case it is erroneously set to 10%

I totally agree! Since I only own the Warema-Lights, I'm not sure if this is the 'normal' homee behaviour. I don't think it's an error with the library, since it's the same with the homee app: When I switch on the light using the on/off switch, it automatically goes directly to 100%, no matter what's the last dimming value - if I want to switch it on with e.g. 50%, I have to use the dimming slider.

**Comment by Taraman17** [comment]
It looks like all lights turn on if a dimming value is sent - so I try to change it according to your suggestion.

It's in the new beta release.

**Comment by Taraman17** [comment]
fixed with #49
