### ISSUE TITLE
Error in receive handler: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

### ISSUE THREAD

**Issue by Wesie** [Taraman17/hass-homee#31]
## Type of problem

- [ ] I have a question.
- [ ] A feature does not work as expected.
- [X] I found a bug (see error log below).

## Version
newest

## Detailed description

Following new warning messages are availabel with the newest version:
**_Error in receive handler: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Could not iterate over relationships:_**

## Error log
Logger: pymee
Source: runner.py:179
First occurred: 08:05:05 (2 occurrences)
Last logged: 08:05:12

Error in receive handler: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Could not iterate over relationships: [{'id': 5, 'group_id': 1, 'node_id': 0, 'homeegram_id': 4, 'order': 0}, {'id': 8, 'group_id': 1, 'node_id': 6, 'homeegram_id': 0, 'order': 0}, {'id': 14, 'group_id': 3, 'node_id': 8, 'homeegram_id': 0, 'order': 0}, {'id': 16, 'group_id': 2, 'node_id': 9, 'homeegram_id': 0, 'order': 0}, {'id': 27, 'group_id': 3, 'node_id': 11, 'homeegram_id': 0, 'order': 0}, {'id': 28, 'group_id': 3, 'node_id': 0, 'homeegram_id': 17, 'order': 0}, {'id': 29, 'group_id': 3, 'node_id': 0, 'homeegram_id': 18, 'order': 0}, {'id': 30, 'group_id': 2, 'node_id': 12, 'homeegram_id': 0, 'order': 0}, {'id': 31, 'group_id': 2, 'node_id': 0, 'homeegram_id': 19, 'order': 0}, {'id': 33, 'group_id': 2, 'node_id': 13, 'homeegram_id': 0, 'order': 0}, {'id': 34, 'group_id': 2, 'node_id': 0, 'homeegram_id': 22, 'order': 0}, {'id': 35, 'group_id': 2, 'node_id': 0, 'homeegram_id': 23, 'order': 0}, {'id': 38, 'group_id': 2, 'node_id': 0, 'homeegram_id': 28, 'order': 0}, {'id': 39, 'group_id': 2, 'node_id': 0, 'homeegram_id': 31, 'order': 0}, {'id': 40, 'group_id': 2, 'node_id': 0, 'homeegram_id': 32, 'order': 0}, {'id': 45, 'group_id': 2, 'node_id': 0, 'homeegram_id': 35, 'order': 0}, {'id': 46, 'group_id': 8, 'node_id': 16, 'homeegram_id': 0, 'order': 0}, {'id': 47, 'group_id': 12, 'node_id': 9, 'homeegram_id': 0, 'order': 0}, {'id': 48, 'group_id': 12, 'node_id': 12, 'homeegram_id': 0, 'order': 0}, {'id': 49, 'group_id': 12, 'node_id': 13, 'homeegram_id': 0, 'order': 0}, {'id': 50, 'group_id': 12, 'node_id': 0, 'homeegram_id': 22, 'order': 0}, {'id': 51, 'group_id': 12, 'node_id': 0, 'homeegram_id': 23, 'order': 0}, {'id': 53, 'group_id': 12, 'node_id': 0, 'homeegram_id': 31, 'order': 0}, {'id': 54, 'group_id': 12, 'node_id': 0, 'homeegram_id': 32, 'order': 0}, {'id': 55, 'group_id': 12, 'node_id': 0, 'homeegram_id': 35, 'order': 0}, {'id': 56, 'group_id': 12, 'node_id': 0, 'homeegram_id': 19, 'order': 0}, {'id': 57, 'group_id': 2, 'node_id': 0, 'homeegram_id': 36, 'order': 0}, {'id': 58, 'group_id': 12, 'node_id': 0, 'homeegram_id': 36, 'order': 0}, {'id': 62, 'group_id': 3, 'node_id': 17, 'homeegram_id': 0, 'order': 0}, {'id': 63, 'group_id': 3, 'node_id': 0, 'homeegram_id': 43, 'order': 0}, {'id': 64, 'group_id': 3, 'node_id': 0, 'homeegram_id': 44, 'order': 0}, {'id': 65, 'group_id': 13, 'node_id': 6, 'homeegram_id': 0, 'order': 0}, {'id': 66, 'group_id': 13, 'node_id': 0, 'homeegram_id': 37, 'order': 0}, {'id': 67, 'group_id': 13, 'node_id': 0, 'homeegram_id': 39, 'order': 0}, {'id': 68, 'group_id': 3, 'node_id': 0, 'homeegram_id': 45, 'order': 0}, {'id': 71, 'group_id': 3, 'node_id': 20, 'homeegram_id': 0, 'order': 0}, {'id': 72, 'group_id': 28, 'node_id': 22, 'homeegram_id': 0, 'order': 0}, {'id': 76, 'group_id': 5, 'node_id': 21, 'homeegram_id': 0, 'order': 0}, {'id': 78, 'group_id': 7, 'node_id': 23, 'homeegram_id': 0, 'order': 0}, {'id': 80, 'group_id': 7, 'node_id': 0, 'homeegram_id': 52, 'order': 0}, {'id': 81, 'group_id': 7, 'node_id': 0, 'homeegram_id': 53, 'order': 0}, {'id': 86, 'group_id': 28, 'node_id': 0, 'homeegram_id': 57, 'order': 0}, {'id': 87, 'group_id': 28, 'node_id': 0, 'homeegram_id': 58, 'order': 0}, {'id': 91, 'group_id': 3, 'node_id': 0, 'homeegram_id': 60, 'order': 0}, {'id': 98, 'group_id': 5, 'node_id': 0, 'homeegram_id': 65, 'order': 0}, {'id': 104, 'group_id': 4, 'node_id': 3, 'homeegram_id': 0, 'order': 0}, {'id': 105, 'group_id': 4, 'node_id': 14, 'homeegram_id': 0, 'order': 0}, {'id': 106, 'group_id': 4, 'node_id': 15, 'homeegram_id': 0, 'order': 0}, {'id': 107, 'group_id': 5, 'node_id': 0, 'homeegram_id': 66, 'order': 0}, {'id': 108, 'group_id': 4, 'node_id': 0, 'homeegram_id': 64, 'order': 0}, {'id': 109, 'group_id': 4, 'node_id': 0, 'homeegram_id': 67, 'order': 0}, {'id': 111, 'group_id': 5, 'node_id': 22, 'homeegram_id': 0, 'order': 0}, {'id': 112, 'group_id': 5, 'node_id': 3, 'homeegram_id': 0, 'order': 0}, {'id': 115, 'group_id': 30, 'node_id': 8, 'homeegram_id': 0, 'order': 0}, {'id': 118, 'group_id': 5, 'node_id': 0, 'homeegram_id': 69, 'order': 0}, {'id': 119, 'group_id': 4, 'node_id': 0, 'homeegram_id': 68, 'order': 0}, {'id': 120, 'group_id': 30, 'node_id': 27, 'homeegram_id': 0, 'order': 0}, {'id': 121, 'group_id': 28, 'node_id': 18, 'homeegram_id': 0, 'order': 0}, {'id': 123, 'group_id': 28, 'node_id': 20, 'homeegram_id': 0, 'order': 0}, {'id': 124, 'group_id': 28, 'node_id': 21, 'homeegram_id': 0, 'order': 0}, {'id': 133, 'group_id': 19, 'node_id': 22, 'homeegram_id': 0, 'order': 0}, {'id': 135, 'group_id': 28, 'node_id': 0, 'homeegram_id': 70, 'order': 0}, {'id': 136, 'group_id': 28, 'node_id': 0, 'homeegram_id': 71, 'order': 0}, {'id': 137, 'group_id': 28, 'node_id': 0, 'homeegram_id': 72, 'order': 0}, {'id': 142, 'group_id': 24, 'node_id': 21, 'homeegram_id': 0, 'order': 0}, {'id': 143, 'group_id': 25, 'node_id': 18, 'homeegram_id': 0, 'order': 0}, {'id': 145, 'group_id': 27, 'node_id': 20, 'homeegram_id': 0, 'order': 0}, {'id': 148, 'group_id': 2, 'node_id': 0, 'homeegram_id': 74, 'order': 0}, {'id': 149, 'group_id': 11, 'node_id': 16, 'homeegram_id': 0, 'order': 0}, {'id': 153, 'group_id': 8, 'node_id': 0, 'homeegram_id': 78, 'order': 0}, {'id': 154, 'group_id': 30, 'node_id': 34, 'homeegram_id': 0, 'order': 0}, {'id': 155, 'group_id': 30, 'node_id': 7, 'homeegram_id': 0, 'order': 0}, {'id': 156, 'group_id': 7, 'node_id': 7, 'homeegram_id': 0, 'order': 0}, {'id': 157, 'group_id': 12, 'node_id': 0, 'homeegram_id': 79, 'order': 0}, {'id': 159, 'group_id': 3, 'node_id': 0, 'homeegram_id': 81, 'order': 0}, {'id': 160, 'group_id': 34, 'node_id': 14, 'homeegram_id': 0, 'order': 0}, {'id': 161, 'group_id': 34, 'node_id': 15, 'homeegram_id': 0, 'order': 0}, {'id': 162, 'group_id': 34, 'node_id': 23, 'homeegram_id': 0, 'order': 0}, {'id': 163, 'group_id': 7, 'node_id': 35, 'homeegram_id': 0, 'order': 0}, {'id': 164, 'group_id': 26, 'node_id': 35, 'homeegram_id': 0, 'order': 0}, {'id': 165, 'group_id': 14, 'node_id': 35, 'homeegram_id': 0, 'order': 0}, {'id': 167, 'group_id': 28, 'node_id': 35, 'homeegram_id': 0, 'order': 0}, {'id': 168, 'group_id': 36, 'node_id': 36, 'homeegram_id': 0, 'order': 0}, {'id': 170, 'group_id': 6, 'node_id': 0, 'homeegram_id': 84, 'order': 0}, {'id': 171, 'group_id': 28, 'node_id': 0, 'homeegram_id': 84, 'order': 0}, {'id': 175, 'group_id': 7, 'node_id': 0, 'homeegram_id': 86, 'order': 0}, {'id': 176, 'group_id': 28, 'node_id': 0, 'homeegram_id': 86, 'order': 0}, {'id': 177, 'group_id': 5, 'node_id': 0, 'homeegram_id': 87, 'order': 0}, {'id': 178, 'group_id': 28, 'node_id': 0, 'homeegram_id': 87, 'order': 0}, {'id': 179, 'group_id': 28, 'node_id': 0, 'homeegram_id': 88, 'order': 0}, {'id': 180, 'group_id': 3, 'node_id': 0, 'homeegram_id': 88, 'order': 0}, {'id': 181, 'group_id': 5, 'node_id': 0, 'homeegram_id': 72, 'order': 0}, {'id': 182, 'group_id': 5, 'node_id': 0, 'homeegram_id': 71, 'order': 0}, {'id': 183, 'group_id': 5, 'node_id': 0, 'homeegram_id': 70, 'order': 0}, {'id': 184, 'group_id': 6, 'node_id': 18, 'homeegram_id': 0, 'order': 0}, {'id': 185, 'group_id': 8, 'node_id': 36, 'homeegram_id': 0, 'order': 0}, {'id': 186, 'group_id': 8, 'node_id': 9, 'homeegram_id': 0, 'order': 0}, {'id': 187, 'group_id': 8, 'node_id': 34, 'homeegram_id': 0, 'order': 0}, {'id': 188, 'group_id': 36, 'node_id': 39, 'homeegram_id': 0, 'order': 0}, {'id': 189, 'group_id': 36, 'node_id': 0, 'homeegram_id': 89, 'order': 0}, {'id': 190, 'group_id': 8, 'node_id': 0, 'homeegram_id': 90, 'order': 0}, {'id': 191, 'group_id': 36, 'node_id': 0, 'homeegram_id': 90, 'order': 0}, {'id': 192, 'group_id': 8, 'node_id': 0, 'homeegram_id': 89, 'order': 0}, {'id': 193, 'group_id': 11, 'node_id': 39, 'homeegram_id': 0, 'order': 0}, {'id': 194, 'group_id': 8, 'node_id': 39, 'homeegram_id': 0, 'order': 0}, {'id': 195, 'group_id': 11, 'node_id': 36, 'homeegram_id': 0, 'order': 0}, {'id': 196, 'group_id': 7, 'node_id': 40, 'homeegram_id': 0, 'order': 0}, {'id': 197, 'group_id': 28, 'node_id': 40, 'homeegram_id': 0, 'order': 0}, {'id': 198, 'group_id': 28, 'node_id': 0, 'homeegram_id': 91, 'order': 0}, {'id': 200, 'group_id': 7, 'node_id': 0, 'homeegram_id': 91, 'order': 0}, {'id': 201, 'group_id': 28, 'node_id': 0, 'homeegram_id': 92, 'order': 0}, {'id': 203, 'group_id': 28, 'node_id': 0, 'homeegram_id': 93, 'order': 0}, {'id': 205, 'group_id': 7, 'node_id': 0, 'homeegram_id': 93, 'order': 0}, {'id': 206, 'group_id': 7, 'node_id': 0, 'homeegram_id': 92, 'order': 0}, {'id': 209, 'group_id': 15, 'node_id': 21, 'homeegram_id': 0, 'order': 0}, {'id': 213, 'group_id': 28, 'node_id': 41, 'homeegram_id': 0, 'order': 0}, {'id': 214, 'group_id': 6, 'node_id': 41, 'homeegram_id': 0, 'order': 0}, {'id': 215, 'group_id': 28, 'node_id': 0, 'homeegram_id': 94, 'order': 0}, {'id': 217, 'group_id': 28, 'node_id': 0, 'homeegram_id': 95, 'order': 0}, {'id': 219, 'group_id': 28, 'node_id': 0, 'homeegram_id': 96, 'order': 0}, {'id': 221, 'group_id': 6, 'node_id': 0, 'homeegram_id': 96, 'order': 0}, {'id': 222, 'group_id': 6, 'node_id': 0, 'homeegram_id': 95, 'order': 0}, {'id': 223, 'group_id': 6, 'node_id': 0, 'homeegram_id': 94, 'order': 0}, {'id': 224, 'group_id': 19, 'node_id': 40, 'homeegram_id': 0, 'order': 0}, {'id': 225, 'group_id': 19, 'node_id': 41, 'homeegram_id': 0, 'order': 0}, {'id': 227, 'group_id': 16, 'node_id': 18, 'homeegram_id': 0, 'order': 0}, {'id': 228, 'group_id': 16, 'node_id': 20, 'homeegram_id': 0, 'order': 0}, {'id': 229, 'group_id': 16, 'node_id': 21, 'homeegram_id': 0, 'order': 0}, {'id': 230, 'group_id': 16, 'node_id': 35, 'homeegram_id': 0, 'order': 0}, {'id': 231, 'group_id': 20, 'node_id': 41, 'homeegram_id': 0, 'order': 0}, {'id': 232, 'group_id': 22, 'node_id': 40, 'homeegram_id': 0, 'order': 0}, {'id': 233, 'group_id': 23, 'node_id': 22, 'homeegram_id': 0, 'order': 0}, {'id': 234, 'group_id': 28, 'node_id': 43, 'homeegram_id': 0, 'order': 0}, {'id': 235, 'group_id': 3, 'node_id': 43, 'homeegram_id': 0, 'order': 0}, {'id': 236, 'group_id': 28, 'node_id': 0, 'homeegram_id': 97, 'order': 0}, {'id': 238, 'group_id': 3, 'node_id': 0, 'homeegram_id': 97, 'order': 0}, {'id': 239, 'group_id': 28, 'node_id': 0, 'homeegram_id': 98, 'order': 0}, {'id': 241, 'group_id': 3, 'node_id': 0, 'homeegram_id': 98, 'order': 0}, {'id': 242, 'group_id': 28, 'node_id': 0, 'homeegram_id': 99, 'order': 0}, {'id': 244, 'group_id': 3, 'node_id': 0, 'homeegram_id': 99, 'order': 0}, {'id': 245, 'group_id': 3, 'node_id': 0, 'homeegram_id': 100, 'order': 0}, {'id': 246, 'group_id': 28, 'node_id': 0, 'homeegram_id': 100, 'order': 0}, {'id': 247, 'group_id': 5, 'node_id': 0, 'homeegram_id': 101, 'order': 0}, {'id': 248, 'group_id': 28, 'node_id': 0, 'homeegram_id': 101, 'order': 0}, {'id': 249, 'group_id': 7, 'node_id': 0, 'homeegram_id': 102, 'order': 0}, {'id': 250, 'group_id': 28, 'node_id': 0, 'homeegram_id': 102, 'order': 0}, {'id': 251, 'group_id': 6, 'node_id': 0, 'homeegram_id': 103, 'order': 0}, {'id': 252, 'group_id': 28, 'node_id': 0, 'homeegram_id': 103, 'order': 0}, {'id': 253, 'group_id': 11, 'node_id': 44, 'homeegram_id': 0, 'order': 0}, {'id': 263, 'group_id': 4, 'node_id': 27, 'homeegram_id': 0, 'order': 0}, {'id': 264, 'group_id': 5, 'node_id': 27, 'homeegram_id': 0, 'order': 0}, {'id': 271, 'group_id': 8, 'node_id': 45, 'homeegram_id': 0, 'order': 0}, {'id': 272, 'group_id': 34, 'node_id': 45, 'homeegram_id': 0, 'order': 0}, {'id': 273, 'group_id': 2, 'node_id': 0, 'homeegram_id': 104, 'order': 0}, {'id': 274, 'group_id': 8, 'node_id': 0, 'homeegram_id': 104, 'order': 0}, {'id': 275, 'group_id': 12, 'node_id': 0, 'homeegram_id': 104, 'order': 0}, {'id': 279, 'group_id': 8, 'node_id': 0, 'homeegram_id': 109, 'order': 0}, {'id': 280, 'group_id': 8, 'node_id': 0, 'homeegram_id': 110, 'order': 0}, {'id': 281, 'group_id': 39, 'node_id': 12, 'homeegram_id': 0, 'order': 0}, {'id': 282, 'group_id': 39, 'node_id': 43, 'homeegram_id': 0, 'order': 0}, {'id': 283, 'group_id': 39, 'node_id': 37, 'homeegram_id': 0, 'order': 0}, {'id': 284, 'group_id': 39, 'node_id': 13, 'homeegram_id': 0, 'order': 0}, {'id': 285, 'group_id': 39, 'node_id': 22, 'homeegram_id': 0, 'order': 0}, {'id': 286, 'group_id': 39, 'node_id': 21, 'homeegram_id': 0, 'order': 0}, {'id': 287, 'group_id': 39, 'node_id': 41, 'homeegram_id': 0, 'order': 0}, {'id': 288, 'group_id': 39, 'node_id': 18, 'homeegram_id': 0, 'order': 0}, {'id': 289, 'group_id': 39, 'node_id': 40, 'homeegram_id': 0, 'order': 0}, {'id': 290, 'group_id': 39, 'node_id': 35, 'homeegram_id': 0, 'order': 0}, {'id': 291, 'group_id': 39, 'node_id': 38, 'homeegram_id': 0, 'order': 0}, {'id': 292, 'group_id': 39, 'node_id': 20, 'homeegram_id': 0, 'order': 0}, {'id': 294, 'group_id': 39, 'node_id': 3, 'homeegram_id': 0, 'order': 0}, {'id': 295, 'group_id': 39, 'node_id': 9, 'homeegram_id': 0, 'order': 0}, {'id': 296, 'group_id': 39, 'node_id': 36, 'homeegram_id': 0, 'order': 0}, {'id': 299, 'group_id': 40, 'node_id': 2, 'homeegram_id': 0, 'order': 0}, {'id': 300, 'group_id': 19, 'node_id': 43, 'homeegram_id': 0, 'order': 0}, {'id': 301, 'group_id': 9, 'node_id': 48, 'homeegram_id': 0, 'order': 0}, {'id': 302, 'group_id': 9, 'node_id': 0, 'homeegram_id': 89, 'order': 0}, {'id': 303, 'group_id': 39, 'node_id': 48, 'homeegram_id': 0, 'order': 0}, {'id': 304, 'group_id': 11, 'node_id': 48, 'homeegram_id': 0, 'order': 0}, {'id': 305, 'group_id': 36, 'node_id': 48, 'homeegram_id': 0, 'order': 0}, {'id': 306, 'group_id': 9, 'node_id': 49, 'homeegram_id': 0, 'order': 0}, {'id': 309, 'group_id': 9, 'node_id': 0, 'homeegram_id': 113, 'order': 0}, {'id': 311, 'group_id': 6, 'node_id': 6, 'homeegram_id': 0, 'order': 0}, {'id': 313, 'group_id': 41, 'node_id': 44, 'homeegram_id': 0, 'order': 0}, {'id': 314, 'group_id': 36, 'node_id': 44, 'homeegram_id': 0, 'order': 0}, {'id': 315, 'group_id': 9, 'node_id': 0, 'homeegram_id': 116, 'order': 0}, {'id': 316, 'group_id': 9, 'node_id': 0, 'homeegram_id': 117, 'order': 0}, {'id': 317, 'group_id': 5, 'node_id': 50, 'homeegram_id': 0, 'order': 0}, {'id': 318, 'group_id': 42, 'node_id': 50, 'homeegram_id': 0, 'order': 0}, {'id': 319, 'group_id': 7, 'node_id': 51, 'homeegram_id': 0, 'order': 0}, {'id': 320, 'group_id': 34, 'node_id': 51, 'homeegram_id': 0, 'order': 0}, {'id': 325, 'group_id': 7, 'node_id': 0, 'homeegram_id': 118, 'order': 0}, {'id': 326, 'group_id': 34, 'node_id': 0, 'homeegram_id': 118, 'order': 0}, {'id': 329, 'group_id': 40, 'node_id': 0, 'homeegram_id': 120, 'order': 0}, {'id': 330, 'group_id': 40, 'node_id': 0, 'homeegram_id': 121, 'order': 0}, {'id': 331, 'group_id': 6, 'node_id': 52, 'homeegram_id': 0, 'order': 0}, {'id': 332, 'group_id': 42, 'node_id': 52, 'homeegram_id': 0, 'order': 0}, {'id': 337, 'group_id': 7, 'node_id': 59, 'homeegram_id': 0, 'order': 0}, {'id': 338, 'group_id': 42, 'node_id': 59, 'homeegram_id': 0, 'order': 0}, {'id': 339, 'group_id': 7, 'node_id': 60, 'homeegram_id': 0, 'order': 0}, {'id': 340, 'group_id': 7, 'node_id': 0, 'homeegram_id': 1, 'order': 0}, {'id': 341, 'group_id': 7, 'node_id': 0, 'homeegram_id': 122, 'order': 0}, {'id': 342, 'group_id': 34, 'node_id': 0, 'homeegram_id': 122, 'order': 0}, {'id': 345, 'group_id': 40, 'node_id': 38, 'homeegram_id': 0, 'order': 0}, {'id': 346, 'group_id': 40, 'node_id': 37, 'homeegram_id': 0, 'order': 0}, {'id': 347, 'group_id': 40, 'node_id': 58, 'homeegram_id': 0, 'order': 0}, {'id': 348, 'group_id': 4, 'node_id': 0, 'homeegram_id': 114, 'order': 0}, {'id': 349, 'group_id': 30, 'node_id': 14, 'homeegram_id': 0, 'order': 0}, {'id': 350, 'group_id': 30, 'node_id': 49, 'homeegram_id': 0, 'order': 0}, {'id': 351, 'group_id': 9, 'node_id': 64, 'homeegram_id': 0, 'order': 0}, {'id': 352, 'group_id': 42, 'node_id': 64, 'homeegram_id': 0, 'order': 0}, {'id': 353, 'group_id': 35, 'node_id': 66, 'homeegram_id': 0, 'order': 0}, {'id': 357, 'group_id': 35, 'node_id': 67, 'homeegram_id': 0, 'order': 0}, {'id': 358, 'group_id': 5, 'node_id': 68, 'homeegram_id': 0, 'order': 0}, {'id': 359, 'group_id': 5, 'node_id': 0, 'homeegram_id': 123, 'order': 0}, {'id': 360, 'group_id': 5, 'node_id': 0, 'homeegram_id': 124, 'order': 0}]

**Comment by Wesie** [comment]
Thx for replay. I'll observe the logs in the next time

**Comment by Taraman17** [comment]
This will be fixed in an upgrade to the latest pymee library version with the next release

**Comment by Taraman17** [comment]
fixed with #39
