### ISSUE TITLE
Integration verliert die Verbindung

### ISSUE THREAD

**Issue by shadow3108** [Taraman17/hass-homee#35]
## Type of problem

- [x] A feature does not work as expected.

## Version
V2.7.0

## Detailed description
Vor dem letzten Update hatte ich mehrmals täglich das Problem, das ich die Integration neustarten musste, weil keine Werte mehr übermittelt wurden und Geräte nicht mehr geschaltet werden konnten.
Mit der Version 2.7.0 ist das extrem verbessert worden (vielen Dank erstmal an der Stelle für deine Arbeit!!) und ich hatte jetzt erst nach ca. 10 Tagen wieder einen Ausfall und musste die Integration neustarten, damit wieder Werte empfangen wurden.
Ob das am Ende ein Problem der Integration oder meines Systems ist, kann ich leider nicht feststellen. In der betroffenen Zeit, habe ich zumindest keinerlei Änderungen am System vorgenommen.

Wenn ich helfen kann, die Ursache dafür zu finden, mache ich das sehr gerne, brauche aber etwas Unterstützung, weil ich HA Anfänger bin.

**Comment by Wesie** [comment]
Das Problem ich gestern das erste Mal (1,5 Monate Laufzeit) auch gehabt. Da mir schon 9 Stunden in der Stromstatistik gefehlt haben, habe ich einen Restart der kompletten HA durchgeführt.

**Comment by Taraman17** [comment]
Mit 2.8.0 wird es ein weiteres Update der für die Netzwerkkommunikation zuständigen Library geben. Dieses behebt den Fehler der bei mir für die Disconnects  verantwortlich war endlich an der Wurzel.
Ob das auch euer Problem ist, wird dann erst die Zeit zeigen.

Auf jeden Fall solltet ihr in den HA logs schauen, ob da einträge von "pymee" auftauchen - das ist die angesprochene Bibliothek. Wenn das der Fall ist, entweder hier posten, oder dirket für pymee ein issue anlegen:
https://github.com/FreshlyBrewedCode/pymee/issues

**Comment by shadow3108** [comment]
Ich sag schon mal schönen Dank!
Bezüglich der Logs, bin ich tatsächlich an dem Punkt schon überfordert... Wo finde ich das und wie kann ich da helfen?
Wenn ich unter Eisntellungen --> System --> Protokolle gehe, zeigt er zwar einige Probleme und Fehler, aber wenn ich oben pymee eingeben, kommt da nix.

**Comment by Taraman17** [comment]
wenn da schon mal pymee nicht auftaucht, dann ist das für mich mal ein gutes zeichen. ;-)

Um genauer hinzusachuen, musst du auf der Logs-Seite ganz unten "Vollständiges protokoll laden" klicken - das kann dann je nach Umfang der Logs einen moment dauern.
Wenn auch darin nichts auftaucht, dann wie in der Readme beschrieben den Loglevel auf Info stellen und nach einem Reconnect erneut schauen. 
Wenn da dann weder pymee noch homee auftaucht, dann wird es schwierig, den schuldigen zu finden. Dann müssen wir uns was einfallen lassen.

**Comment by Taraman17** [comment]
Das ist auf jeden Fall interessant!
Die erste Meldung heißt, das irgendein Gerät von dir mehr als 4 Sensoren für den gleichen Wert hat. Ich bin bisher davon ausgegangen, dass es maximal 4 gibt.
Die Logs von all deinen Geräten habe ich ja noch in einem anderen Issue, da werde ich mal durchschauen, was das ist.

Das mit der sich ändernden Einheit dürfte am letzten Update hängen - da wird statt "n/a" für eine unbekannte Einheit HA-Konform "None" gesetzt. Wenn du dem angegebenen Link folgst, dann solltest du das zurücksetzen können, soweit ich mich erinnere.

**Comment by Wesie** [comment]
Ein interessanter Bug: Das Netzwerk war kurz weg (Router neugestartet) Am nächsten Tag nachgeschaut: Seit dem Zeitpunkt waren keine Daten mehr vorhanden. Sprich, wenn die Netzwerkverbindung zum homee einmal weg ist, word Sie nicht periodisch wieder versucht aufzubauen. Ein Neustart bringt zwar Abhilfe, dürfte jedoch nicht im Sinne des Erfinders sein ;)

**Comment by Taraman17** [comment]
Danke, das ist eine interessante Information. Ich schau mal, ob ich das hier reproduzieren kann.

**Comment by LuiTK** [comment]
Mit der Version 2.8.0 habe ich seit 4 Wochen keine Verbindungsprobleme mehr. Der tägliche homee relaod ist nicht mehr notwendig.
Vielen Dank dafür.

**Comment by shadow3108** [comment]
Bei mir gibt es leider immer noch Probleme und ab und zu ist die Verbindung noch weg. Zuletzt vor 4 Tagen.
Wäre jemand so nett mir zu erklären, wir ich eine Integration überwachen und dann neustarten kann? 
Ich bin da kein Spezialist und bin mit den diversen Anleitungen im Netz nicht weitergekommen.
Das kann natürlich gerne per pn erfolgen, weil ich das mit Sicherheit nicht beim ersten Mal verstehen werde...😇
Am liebsten wäre mir eine Variante die prüft, ob ein bestimmtes Gerät noch Werte sendet und dann ggf. die homee Integration neu läd.
Danke vorab für die Hilfe.

**Comment by Taraman17** [comment]
@shadow3108: Ich vermute dann, das du vielleicht den gleichen Fehler siehst, den Wesie beschrieben hat. Das werde ich mir noch mal anschauen.

PN gibt es in GitHub nicht - du kannst gerne per mail an mozilla(at)adrario.de anfragen.

**Comment by Taraman17** [comment]
> Ein interessanter Bug: Das Netzwerk war kurz weg (Router neugestartet) Am nächsten Tag nachgeschaut: Seit dem Zeitpunkt waren keine Daten mehr vorhanden. Sprich, wenn die Netzwerkverbindung zum homee einmal weg ist, word Sie nicht periodisch wieder versucht aufzubauen. Ein Neustart bringt zwar Abhilfe, dürfte jedoch nicht im Sinne des Erfinders sein ;)

Das Problem konnte ich nachstellen.
Das Backend ist so programmiert, dass es nach 5 reconnect versuchen aufgibt - die sind nach 1:30 min erreicht das reicht bei einem Netzwerkausfall vermutlich in den allerwenigsten Fällen.

**Comment by Taraman17** [comment]
Die neueste Beta hat fixes, die den Reconnect tatsächlich ohne Fehler funktionieren lassen und es gibt jetzt massig Retries - das sollte auch Netzwerk-Ausfälle von einem halben Tag oder länger überbrücken

**Comment by Taraman17** [comment]
Closed with #55
