### ISSUE TITLE
Geräte werden leider fast alle fehlerhaft bzw. mit wenig Funktionen erkannt.

### ISSUE THREAD

**Issue by mupper** [Taraman17/hass-homee#45]
## Type of problem

- [ ] I have a question.
- [X] A feature does not work as expected.
- [X] I found a bug (see error log below).

## Version

Die aktuelle Version
Home Assistant

Core
2024.1.2
Supervisor
2023.12.0
Operating System
11.3
Frontend
20240104.0

## Detailed description
A clear and concise description of the question/problem/bug

Die meisten Geräte werden erkannt. Tür und Fenster (Devolo Aktoren) werden mit Temperatur etc. erkannt. Jedoch wird das öffnen und schließen nicht erkannt. OPEN ist grau als Funktion. Die Geräte sind in einer Gruppe und die Gruppe wurde als Fenster hinzugefügt.

Des Weiteren sind die Schalter und die weiteren Aktoren (Fibaro Flooter etc.) zwar erkannt, jedoch ein großteil der Entitäten sind mit folgenden Merkmalen versehen:

**Diese Entität wird nicht mehr von der Integration homee bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen.**

**Diese Entität ist nicht verfügbar.**

Ich habe das Addon deaktiviert und mehrfach alles neu eingelesen. Keine Chance. Habe in Homee weitere Gruppen erzeigt und für Alexa und HomeKit alles freigegeben, keine Chance.

## Error log

Fehler im Protokoll habe ich massig:

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:368
Integration: Schalter ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 6. Januar 2024 um 18:24:26 (2 occurrences)
Last logged: 09:02:51

Error while setting up homee platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homee/__init__.py", line 290, in state_attributes
    data = self._entity.__class__.__bases__[1].state_attributes.fget(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cached_property' object has no attribute 'fget'

-------------------

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:368
Integration: Binärsensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 6. Januar 2024 um 18:24:24 (2 occurrences)
Last logged: 09:02:51

Error while setting up homee platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homee/__init__.py", line 290, in state_attributes
    data = self._entity.__class__.__bases__[1].state_attributes.fget(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cached_property' object has no attribute 'fget'

--------------------

Die Überswicht sieht dann so aus:
Error doing job: Exception in callback Entity.async_write_ha_state()
09:09:05 – (FEHLER) homee (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal am 6. Januar 2024 um 18:27:39 aufgetreten und erscheint 1426 mal
Error while setting up homee platform for switch
09:02:51 – (FEHLER) Schalter - Die Nachricht ist zum ersten Mal am 6. Januar 2024 um 18:24:26 aufgetreten und erscheint 2 mal
Error while setting up homee platform for number
09:02:51 – (FEHLER) Nummer - Die Nachricht ist zum ersten Mal am 6. Januar 2024 um 18:24:24 aufgetreten und erscheint 2 mal
Error while setting up homee platform for binary_sensor
09:02:51 – (FEHLER) Binärsensor - Die Nachricht ist zum ersten Mal am 6. Januar 2024 um 18:24:24 aufgetreten und erscheint 2 mal
Error adding entities for domain switch with platform homee
09:02:50 – (FEHLER) Schalter - Die Nachricht ist zum ersten Mal am 6. Januar 2024 um 18:24:26 aufgetreten und erscheint 2 mal
Error adding entities for domain number with platform homee
09:02:50 – (FEHLER) Nummer - Die Nachricht ist zum ersten Mal am 6. Januar 2024 um 18:24:24 aufgetreten und erscheint 2 mal
Error adding entities for domain binary_sensor with platform homee
09:02:50 – (FEHLER) Binärsensor - Die Nachricht ist zum ersten Mal am 6. Januar 2024 um 18:24:24 aufgetreten und erscheint 2 mal

```text

Add your logs here.

```

**Comment by springkuh** [comment]
i second this. approx. 90 components imported in home assistant, but most door/window sensors (fibaro, neo coolcam, usw) don't support open/close state.

**Comment by LuiTK** [comment]
Mit dem Update Core 2024.1.2 habe ich den selben Effekt.

**Comment by dnarbflar** [comment]
Ich schließe mich der Runde an. Es klappt leider auch bei mir nicht mit dem aktuellen Core.

**Comment by shadow3108** [comment]
Auch ich schließe mich da mal an.
Ich habe sogar den Effekt, das er Schalter über Automationen weiterhin schaltet, aber das Gerät an sich unter "Einstellungen --> Geräte" nicht verfügbar ist und auch nicht geschaltet werden kann... Das ist mir dann doch sehr suspekt.🙈
Ich nutze Core 2024.1.3 und die homee integration 2.9.0 Beta.1

**Comment by R3tr021** [comment]
Ich habe genau das gleiche Problem. Meine Rolladensteuerung und meine Heizkörper werden noch normal erkannt. Die Fenstersensoren und Lichtschalter allerdings nicht mehr.

**Comment by Taraman17** [comment]
Hallo zusammen,
das sieht aus, als ob in der neuen Version irgendetwas gändert wurde, das diesen Fehler verursacht.

Ich versuche mir das so schnell wie möglich anzuschauen, habe aber aktuell recht wenig Zeit.

**Comment by Taraman17** [comment]
Released https://github.com/Taraman17/hass-homee/tree/v2.9.0-beta.2

**Comment by dnarbflar** [comment]
Vielen Dank. Auf den ersten Blick ist selbst mit dem aktuellem Core alles wieder wie es sein soll ;) Danke für deine Arbeit.

**Comment by Taraman17** [comment]
fixed with #49

**Comment by shadow3108** [comment]
Auch von meiner Seite ein großes Dankeschön!!
Sieht gut aus!

**Comment by springkuh** [comment]
Hi, danke für den Einsatz!
Ich hab die Integration nochmal komplett rausgeworfen, übers Repository neu installiert aber leider fehlen bei den Fenstersensoren immer noch der Status, sprich es sind wie bisher nur als Steuerelemente Aufwachintervall und Watchdog sichtbar und als Sensoren Batterie
Müssen die Geräte nochmal gelöscht werden alle?

**Comment by LuiTK** [comment]
Auch von mir vielen Dank.
Es wird alles korrekt angezeigt.
