### ISSUE TITLE
Dimmable Lights after updating to version 2.9.0 are unavailable

### ISSUE THREAD

**Issue by juergjue** [Taraman17/hass-homee#50]
## Type of problem
- [ ] I found a bug (see error log below).

## Version
2.9.0

## Detailed description
After updating to version 2.9.0 dimmable lights are now unavailable

![299421957-1cca63eb-693e-4485-ae67-76ac2997f439](https://github.com/Taraman17/hass-homee/assets/100994791/e3aa622f-3e16-4ed9-9cc6-dc0f61b95554)

## Error log
(Hope the short log is enough)

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:360
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 19:20:20 (8 occurrences)
Last logged: 21:05:08

Error while setting up homee platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/homee/light.py", line 108, in async_setup_entry
    devices.append(HomeeLight(node, light_set, index, config_entry))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homee/light.py", line 158, in __init__
    self._supported_features = get_light_features(self)
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homee/light.py", line 43, in get_light_features
    features |= ColorMode.BRIGHTNESS
TypeError: unsupported operand type(s) for |=: 'int' and 'ColorMode'

```
Thx for having a look on it.

**Comment by Taraman17** [comment]
Please try the latest beta.
It looks good on my side, but I can't try to control lights, since I don't have any in homee.

**Comment by majacob1** [comment]
I had the same problem (using Warema dimmable lights) - with 2.9.1-beta it's working fine. 
Thanks for the prompt fix!

**Comment by Taraman17** [comment]
Closed with #55
