### ISSUE TITLE
Window sensors do not report open_close state after 2.9.0 (says entity is undefined)

### ISSUE THREAD

**Issue by wisemanny** [Taraman17/hass-homee#52]
## Type of problem

- [ ] I have a question.
- [ ] A feature does not work as expected.
- [x] I found a bug (see error log below).

## Version
2.9.0

## Detailed description
Window sensor say that the entity that represents the state is not available. Seems like here is a mistake:
https://github.com/Taraman17/hass-homee/blob/8baa5480b61b7fbdc79bfdfc42c5a2a99b38675d/custom_components/homee/binary_sensor.py#L53

Should be AttributeType.OPEN_CLOSE. If you agree, I will submit a PR. I did local change and it works now.

**Comment by Taraman17** [comment]
Closed with #55
