### ISSUE TITLE
Danfoss Raumthermostat zeigt nie "untätig", selbst wenn die Solltemperatur erreicht ist.

### ISSUE THREAD

**Issue by Wesie** [Taraman17/hass-homee#69]
## Type of problem

- [ ] I have a question.
- [X] A feature does not work as expected.
- [ ] I found a bug (see error log below).

## Version
2.9.3 beta4

Scheinbar sind beim Danfoss Raumthermostat die Soll und die Isttemperatur vertauscht

Ansicht homee
![Screenshot_20240428_133202_Samsung Internet](https://github.com/Taraman17/hass-homee/assets/9315139/c3b95f46-81f3-4ae9-a857-25693dfa0ff8)

Ansicht HA

![Screenshot_20240428_133224_Firefox](https://github.com/Taraman17/hass-homee/assets/9315139/f5f6c50a-036b-4169-afa1-fd5a94cdbaa8)

**Comment by Taraman17** [comment]
Die Solltemperatur ist bei HA die Große in der Mitte.
Das passt mit dem Bild aus Homee zusammen...

**Comment by Wesie** [comment]
Warum stehen dann alle Raumthermostate im Heizbetrieb, obwohl die Soll geringer ist als die IST Temperatur? Bei den normalen Heizthermostaten, steht korrekterweise "untätig" wenn die Soll Temperatur überschritten ist.

**Comment by Taraman17** [comment]
Da hast du recht, das liegt dann an was anderem.
Aktuell liefert HA "untätig", wenn der Modus auf heizen steht un das Ventil komplett zu ist.
Diese Information fehlt den Danfoss Thermostaten, daher zeigen sie immer "Heizbetrieb" an.
Ich werde das ändern, damit es anhand der Temperatur erkannt wird.

**Comment by Wesie** [comment]
Beta 2.9.3 beta5:  Die Danfoss stehen weiterhin auf Heizbetrieb:
![grafik](https://github.com/Taraman17/hass-homee/assets/9315139/27e0e85b-7768-4182-9bed-dbee25250b8f)

**Comment by Taraman17** [comment]
Mist.
Bei mir mit Testdaten hatte es funktioniert - ich schau noch Mal nach.

**Comment by Taraman17** [comment]
Werte verdreht, wenn du die Solltemperatur über die Aktuelle stellst wird er Untätig zeigen.
Behebe ich.
