### ISSUE TITLE
Eltako Weather Station kein Regensensor

### ISSUE THREAD

**Issue by Milobaby1** [Taraman17/hass-homee#82]
Bei der Eltako Weather Station wird der Regensensor nicht an Home Assistant weitergegeben.

**Comment by Taraman17** [comment]
https://github.com/Taraman17/hass-homee/wiki/Eltako-Weather-Station

**Comment by Taraman17** [comment]
Fixed with Release 2.9.4

**Comment by Milobaby1** [comment]
Danke !!!!!!
Für die Integration........
